import os
import Classes

def include(filename):
    if os.path.exists(filename):
        exec(open(filename).read())


include('Classes.py')

playerColor = input("Would you like to be black or white chess pieces?")

if playerColor == 'black':
    pawn1 = Classes.Pawn('black','2a')
    pawn2 = Classes.Pawn('black', '2b')
    pawn3 = Classes.Pawn('black','2c')
    pawn4 = Classes.Pawn('black', '2d')
    pawn5 = Classes.Pawn('black', '2e')
    pawn6 = Classes.Pawn('black', '2f')
    pawn7 = Classes.Pawn('black', '2g')
    pawn8 = Classes.Pawn('black',  '2h')
    rook1 = Classes.Rook('black', '1a')
    rook2 = Classes.Rook('black', '1h')
    knight1 = Classes.Knight('black', '1b')
    knight2 = Classes.Knight('black', '1g')
    bishop1 = Classes.Bishop('black', '1c')
    bishop2 = Classes.Bishop('black', '1f')
    queen = Classes.Queen('black', '1d')
    king = Classes.King('black', '1e')
    computerpawn1 = Classes.Pawn('white', '7a')
    computerpawn2 = Classes.Pawn('white', '7b')
    computerpawn3 = Classes.Pawn('white', '7c')
    computerpawn4 = Classes.Pawn('white',  '7d')
    computerpawn5 = Classes.Pawn('white', '7e')
    computerpawn6 = Classes.Pawn('white',  '7f')
    computerpawn7 = Classes.Pawn('white', '7g')
    computerpawn8 = Classes.Pawn('white', '7h')
    computerrook1 = Classes.Rook('white', '8a')
    computerrook2 = Classes.Rook('white', '8h')
    computerknight1 = Classes.Knight('white', '8b')
    computerknight2 = Classes.Knight('white',  '8g')
    computerbishop1 = Classes.Bishop('white',  '8c')
    computerbishop2 = Classes.Bishop('white',  '8f')
    computerqueen = Classes.Queen('white', '8d')
    computerking = Classes.King('white', '8e')
else:
    pawn1 = Classes.Pawn('white',  '2a')
    pawn2 = Classes.Pawn('white',  '2b')
    pawn3 = Classes.Pawn('white',  '2c')
    pawn4 = Classes.Pawn('white',  '2d')
    pawn5 = Classes.Pawn('white',  '2e')
    pawn6 = Classes.Pawn('white',  '2f')
    pawn7 = Classes.Pawn('white',  '2g')
    pawn8 = Classes.Pawn('white', '2h')
    rook1 = Classes.Rook('white',  '1a')
    rook2 = Classes.Rook('white',  '1h')
    knight1 = Classes.Knight('white',  '1b')
    knight2 = Classes.Knight('white',  '1g')
    bishop1 = Classes.Bishop('white',  '1c')
    bishop2 = Classes.Bishop('white', '1f')
    queen = Classes.Queen('white',  '1d')
    king = Classes.King('white',  '1e')
    computerpawn1 = Classes.Pawn('black', '7a')
    computerpawn2 = Classes.Pawn('black',  '7b')
    computerpawn3 = Classes.Pawn('black',  '7c')
    computerpawn4 = Classes.Pawn('black',  '7d')
    computerpawn5 = Classes.Pawn('black',  '7e')
    computerpawn6 = Classes.Pawn('black',  '7f')
    computerpawn7 = Classes.Pawn('black',  '7g')
    computerpawn8 = Classes.Pawn('black', '7h')
    computerrook1 = Classes.Rook('black',  '8a')
    computerrook2 = Classes.Rook('black',  '8h')
    computerknight1 = Classes.Knight('black',  '8b')
    computerknight2 = Classes.Knight('black',  '8g')
    computerbishop1 = Classes.Bishop('black',  '8c')
    computerbishop2 = Classes.Bishop('black',  '8f')
    computerqueen = Classes.Queen('black',  '8d')
    computerking = Classes.King('black',  '8e')


